// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {engine} from '../models';
import {main} from '../models';

export function DeleteScene(arg1:string):Promise<void>;

export function ExportScene(arg1:string):Promise<string>;

export function GetDefaultConfig():Promise<config.Config>;

export function GetLocalIPs():Promise<Array<string>>;

export function GetStatus():Promise<engine.Status>;

export function ImportScene():Promise<string>;

export function ListScenes():Promise<Array<string>>;

export function LoadScene(arg1:string):Promise<config.Config>;

export function RenameScene(arg1:string,arg2:string):Promise<void>;

export function SaveScene(arg1:string,arg2:config.Config):Promise<void>;

export function SearchPlaces(arg1:string):Promise<Array<main.LocationSearchResult>>;

export function SelectDirectory(arg1:string,arg2:string):Promise<string>;

export function SelectFile(arg1:string,arg2:string):Promise<string>;

export function StartEngine(arg1:config.Config):Promise<void>;

export function StopEngine():Promise<void>;

export function SyncCurrentConfig(arg1:config.Config):Promise<void>;
