// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteScene(arg1) {
  return window['go']['main']['App']['DeleteScene'](arg1);
}

export function ExportScene(arg1) {
  return window['go']['main']['App']['ExportScene'](arg1);
}

export function GetDefaultConfig() {
  return window['go']['main']['App']['GetDefaultConfig']();
}

export function GetLocalIPs() {
  return window['go']['main']['App']['GetLocalIPs']();
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function ImportScene() {
  return window['go']['main']['App']['ImportScene']();
}

export function ListScenes() {
  return window['go']['main']['App']['ListScenes']();
}

export function LoadScene(arg1) {
  return window['go']['main']['App']['LoadScene'](arg1);
}

export function RenameScene(arg1, arg2) {
  return window['go']['main']['App']['RenameScene'](arg1, arg2);
}

export function SaveScene(arg1, arg2) {
  return window['go']['main']['App']['SaveScene'](arg1, arg2);
}

export function SearchPlaces(arg1) {
  return window['go']['main']['App']['SearchPlaces'](arg1);
}

export function SelectDirectory(arg1, arg2) {
  return window['go']['main']['App']['SelectDirectory'](arg1, arg2);
}

export function SelectFile(arg1, arg2) {
  return window['go']['main']['App']['SelectFile'](arg1, arg2);
}

export function StartEngine(arg1) {
  return window['go']['main']['App']['StartEngine'](arg1);
}

export function StopEngine() {
  return window['go']['main']['App']['StopEngine']();
}

export function SyncCurrentConfig(arg1) {
  return window['go']['main']['App']['SyncCurrentConfig'](arg1);
}
